version: '3.6'

volumes:
  navidrome_data:

services:

  navidrome:
    container_name: "navidrome"
    build: 
      context: ../../
      dockerfile: Dockerfile
    restart: unless-stopped
    # user: 1000:1000
    ports:
      - "4533:4533"
    volumes:
      - "/tmp/navidrome_data:/data"
      - "/tmp/navidrome_music:/music:ro"
